import type { SectionConfig } from "./types";

const slug = { name: "slug", label: "URL slug", type: "text", required: true, pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$", placeholder: "lowercase-words", help: "Used in the public page URL." } as const;
const featured = { name: "featured", label: "Featured", type: "boolean", default: false } as const;
const publishing = [
  { name: "status", label: "Publishing status", type: "select", required: true, default: "draft", options: ["draft", "review", "published", "archived"], help: "Only published records appear on the English website." },
  { name: "translationStatus", label: "Persian translation status", type: "select", required: true, default: "draft", options: ["draft", "review", "published", "archived"], help: "Persian pages only show records with an approved published translation." },
  { name: "publishedAt", label: "Publication date", type: "date", help: "Optional editorial publication date." },
  { name: "reviewedAt", label: "Last reviewed", type: "date", help: "Date the content was last checked for accuracy." },
  { name: "reviewer", label: "Reviewer", type: "text", help: "Named content or clinical reviewer." },
] as const;

export const SECTIONS: Record<string, SectionConfig> = {
  board: {
    id: "board", label: "Research board", description: "Research-board and scientific leadership profiles", fileName: "board.json", primaryKey: "slug", titleField: "name", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "name", label: "Full name", type: "text", required: true, localized: true }, { name: "role", label: "Board role", type: "text", required: true, localized: true }, { name: "credentials", label: "Credentials", type: "text", localized: true }, { name: "specialty", label: "Specialty", type: "text", required: true, localized: true }, { name: "institution", label: "Institution", type: "text", required: true, localized: true }, { name: "city", label: "City / country", type: "text", localized: true }, { name: "biography", label: "Professional biography", type: "textarea", required: true, localized: true }, { name: "education", label: "Academic history", type: "array", localized: true, help: "One qualification per line." }, { name: "appointments", label: "Current appointments", type: "array", localized: true, help: "One appointment per line." }, { name: "researchInterests", label: "Research interests", type: "array", localized: true }, { name: "selectedPublications", label: "Selected publications", type: "array", localized: true, help: "Citation and URL where available, one per line." }, { name: "googleScholar", label: "Google Scholar URL", type: "url" }, { name: "orcid", label: "ORCID URL", type: "url" }, { name: "pubmed", label: "PubMed profile / search URL", type: "url" }, { name: "website", label: "Institutional profile URL", type: "url" }, { name: "email", label: "Approved public email", type: "text" }, { name: "phone", label: "Approved public phone", type: "text" }, { name: "photo", label: "Portrait path or URL", type: "text", help: "Use an approved local /images/... path or an authorized https URL." }, { name: "profileConsent", label: "Approved for public profile", type: "boolean", default: false }, { name: "displayOrder", label: "Display order", type: "number", default: 100 }, featured],
  },
  events: {
    id: "events", label: "Events", description: "Scientific meetings and educational events", fileName: "events.json", primaryKey: "slug", titleField: "title", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "title", label: "Event title", type: "text", required: true, localized: true }, { name: "date", label: "Start date", type: "date", required: true }, { name: "endDate", label: "End date", type: "date" }, { name: "location", label: "Location", type: "text", required: true, localized: true }, { name: "type", label: "Event type", type: "select", required: true, localized: true, options: ["Scientific Meeting", "Educational Workshop", "Seminar", "Conference"] }, { name: "description", label: "Description", type: "textarea", required: true, localized: true }, featured, { name: "registrationOpen", label: "Registration open", type: "boolean", default: false }, { name: "registrationMode", label: "Registration mode", type: "select", default: "internal", options: ["internal", "external", "closed"], help: "Internal uses the KRISM form; external opens another website." }, { name: "registrationUrl", label: "External registration URL", type: "url" }, { name: "registrationDeadline", label: "Registration deadline", type: "date" }, { name: "capacity", label: "Capacity", type: "number" }],
  },
  research: {
    id: "research", label: "Research", description: "Projects, studies and collaborations", fileName: "research.json", primaryKey: "slug", titleField: "title", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "title", label: "Project title", type: "text", required: true, localized: true }, { name: "description", label: "Description", type: "textarea", required: true, localized: true }, { name: "location", label: "Study location", type: "text", localized: true }, { name: "date", label: "Start date", type: "date" }, { name: "type", label: "Project type", type: "select", required: true, localized: true, options: ["Observational study", "Clinical study", "Survey", "Registry", "Collaboration", "Systematic review"] }, { name: "statusLabel", label: "Project status", type: "select", options: ["Planning", "Recruiting", "Active", "Analysis", "Completed"] }, { name: "leadInvestigators", label: "Lead investigators", type: "array", localized: true, help: "One investigator per line." }, { name: "collaborators", label: "Collaborators / institutions", type: "array", localized: true, help: "One collaborator per line." }, { name: "funding", label: "Funding", type: "text", localized: true }, { name: "ethicsReference", label: "Ethics reference", type: "text" }, { name: "projectUrl", label: "Project URL", type: "url" }, featured],
  },
  awareness: {
    id: "awareness", label: "Sleep awareness", description: "Public sleep-health articles", fileName: "awareness.json", primaryKey: "slug", titleField: "title", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "title", label: "Article title", type: "text", required: true, localized: true }, { name: "excerpt", label: "Excerpt", type: "textarea", required: true, localized: true }, { name: "category", label: "Category", type: "select", required: true, localized: true, options: ["Sleep Health", "Sleep Disorders", "Healthy Sleep"] }, { name: "content", label: "Article paragraphs", type: "array", required: true, localized: true, help: "One paragraph per line." }, { name: "author", label: "Author", type: "text", localized: true }, { name: "references", label: "References", type: "array", help: "One source or URL per line." }, featured],
  },
  resources: {
    id: "resources", label: "Resources", description: "Educational and clinical resources", fileName: "resources.json", primaryKey: "slug", titleField: "title", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "title", label: "Resource title", type: "text", required: true, localized: true }, { name: "category", label: "Category", type: "select", required: true, localized: true, options: ["Sleep deprivation", "Sleep health", "Guideline", "Educational", "Clinical", "Research", "Public", "External"] }, { name: "description", label: "Description", type: "textarea", required: true, localized: true }, { name: "audience", label: "Audience", type: "select", options: ["Public", "Professionals", "Researchers", "All audiences"] }, { name: "source", label: "Source organization", type: "text", localized: true }, { name: "url", label: "Official source URL", type: "url", required: true }, { name: "internalPage", label: "Publish as KRISM learning page", type: "boolean", default: false }, { name: "graphic", label: "Learning graphic", type: "select", options: ["deprivation", "body-clock", "health-effects", "duration", "habits", "diary", "healthy-need"] }, { name: "readTime", label: "Reading time", type: "text", localized: true, placeholder: "4 min read" }, { name: "content", label: "Learning-page paragraphs", type: "array", localized: true, help: "One paragraph per line. Write an original summary and retain the official source URL above." }, { name: "takeaways", label: "Key ideas", type: "array", localized: true, help: "One short evidence-based point per line." }, { name: "practicalSteps", label: "Practical steps", type: "array", localized: true, help: "One action per line." }, { name: "warningSigns", label: "When to seek help", type: "array", localized: true, help: "One sign per line. Do not diagnose." }, { name: "relatedSlugs", label: "Related resource slugs", type: "array", help: "One internal resource slug per line." }, { name: "downloadUrl", label: "Original download URL", type: "url" }, featured],
  },
  network: {
    id: "network", label: "Professional network", description: "Members, organizations and institutions", fileName: "network.json", primaryKey: "slug", titleField: "name", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "name", label: "Name", type: "text", required: true, localized: true }, { name: "type", label: "Member type", type: "select", required: true, localized: true, options: ["Professional", "Researcher", "Organization", "Institution"] }, { name: "credentials", label: "Credentials", type: "text", localized: true }, { name: "specialty", label: "Specialty", type: "text", localized: true }, { name: "affiliation", label: "Affiliation", type: "text", localized: true }, { name: "city", label: "City", type: "text", localized: true }, { name: "languages", label: "Languages", type: "array", localized: true }, { name: "description", label: "Description", type: "textarea", required: true, localized: true }, { name: "website", label: "Public website", type: "url" }, { name: "publicConsent", label: "Approved for public directory", type: "boolean", default: false }, featured],
  },
  publications: {
    id: "publications", label: "Publications", description: "Scientific publications and contributions", fileName: "publications.json", primaryKey: "slug", titleField: "title", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "title", label: "Publication title", type: "text", required: true, localized: true }, { name: "authors", label: "Authors", type: "text", required: true, localized: true }, { name: "journal", label: "Journal", type: "text", required: true, localized: true }, { name: "year", label: "Year", type: "number", required: true }, { name: "category", label: "Category", type: "text", localized: true }, { name: "doi", label: "DOI", type: "text" }, { name: "pmid", label: "PubMed ID", type: "text" }, { name: "abstract", label: "Abstract", type: "textarea", localized: true }, { name: "url", label: "Publication URL", type: "url", required: true }],
  },
  organizations: {
    id: "organizations", label: "Organizations", description: "Partner organizations", fileName: "organizations.json", primaryKey: "slug", titleField: "name", roles: ["admin", "editor", "viewer"],
    fields: [slug, ...publishing, { name: "name", label: "Organization name", type: "text", required: true, localized: true }, { name: "type", label: "Organization type", type: "text", required: true, localized: true }, { name: "relationship", label: "Relationship", type: "select", required: true, options: ["Member", "Partner", "Scientific reference", "Public institution"] }, { name: "description", label: "Description", type: "textarea", required: true, localized: true }, { name: "website", label: "Website", type: "url", required: true }],
  },
};

export function getSection(sectionId: string): SectionConfig {
  const section = SECTIONS[sectionId];
  if (!section) throw new Error("Unknown content section");
  return section;
}
